select * from customer limit 20

--Q1. what is the total revenue generated by male vs. female customers?
SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue 
FROM customer 
GROUP BY "Gender";

-- 2. Discounted customers with above average spend
SELECT "Customer ID", "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes' 
AND "Purchase Amount (USD)" >= (SELECT AVG("Purchase Amount (USD)") FROM customer);

-- 3. Top 5 products by highest average review rating
SELECT "Item Purchased", AVG("Review Rating") AS average_rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY average_rating DESC
LIMIT 5;

-- 4. Average Purchase Amount: Standard vs Express Shipping
SELECT "Shipping Type", AVG("Purchase Amount (USD)") AS average_purchase
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";

-- 5. Subscribed vs Non-Subscribed spend
SELECT "Subscription Status", AVG("Purchase Amount (USD)") AS average_spend
FROM customer
GROUP BY "Subscription Status";

-- 6. Top 5 products with most discounts
SELECT "Item Purchased", COUNT(*) AS discount_count
FROM customer
WHERE "Discount Applied" = 'Yes'
GROUP BY "Item Purchased"
ORDER BY discount_count DESC
LIMIT 5;

-- 7. Customer Segmentation (New, Returning, Loyal)
SELECT "Customer ID", "Previous Purchases",
CASE 
    WHEN "Previous Purchases" = 0 THEN 'New'
    WHEN "Previous Purchases" BETWEEN 1 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment
FROM customer;

-- 8. Top products in each category
SELECT "Category", "Item Purchased", COUNT(*) as purchase_count
FROM customer
GROUP BY "Category", "Item Purchased"
ORDER BY "Category", purchase_count DESC;

-- 9. Repeat buyers and subscription status
SELECT "Subscription Status", COUNT(*) as customer_count
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

-- 10. Revenue by Age Group
SELECT 
    CASE 
        WHEN "Age" < 20 THEN 'Under 20'
        WHEN "Age" BETWEEN 20 AND 40 THEN '20-40'
        WHEN "Age" BETWEEN 41 AND 60 THEN '41-60'
        ELSE '60+' 
    END AS age_group,
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;